DROP TABLE BBS;
CREATE TABLE BBS
(
    BBS_NO NUMBER PRIMARY KEY,
    WRITER VARCHAR2(100 BYTE) NOT NULL,
    TITLE VARCHAR2(100 BYTE) NOT NULL,
    CONTENT VARCHAR2(4000 BYTE),
    CREATED VARCHAR2(10 BYTE),
    MODIFIED VARCHAR2(10 BYTE)
);

DROP SEQUENCE BBS_SEQ;
CREATE SEQUENCE BBS_SEQ NOCACHE;